# Use bash instead of shell (default)
SHELL := /bin/bash

install:
	echo -e "Installing" > src/install;
lint:
	echo -e "Linting" > src/lint;
check:
	echo -e "Checking" > src/check;
test:
	echo -e "Testing" > src/test;
