# Use bash instead of shell (default)
SHELL := /bin/bash

install:
	echo -e "Installing" > {{cookiecutter.module_name}}/install;
lint:
	echo -e "Linting" > {{cookiecutter.module_name}}/lint;
check:
	echo -e "Checking" > {{cookiecutter.module_name}}/check;
test:
	echo -e "Testing" > {{cookiecutter.module_name}}/test;
